# 3-SRM 641 Week 3 Pandas

## How to load and analyze data using Pandas

In this notebook, we will use the earthquakes data you downloaded using API requests (2-SRM 641 Week 3 Pandas notebook 2) to learn how to:
- load data using Pandas
- Inspecting and manipulating the data
- Summarizing and subsetting the data



We will be working with the data/earthquakes.csv file again, so we need to handle our imports and read it in.

In [1]:
# Load libraries

import numpy as np
import pandas as pd

## Load the Data

Pandas features a number of functions for reading tabular data as a DataFrame object `pandas.read_csv` is one of the most frequently used type depending on your data format. For more info on data types and how to load them check https://wesmckinney.com/book/accessing-data

In [3]:
# load the earthquakes data

df = pd.read_csv('earthquakes.csv') #note the path, my file is saved in the same jupyter notebook folder.

#df = pd.read_csv('data/earthquakes.csv') if your file is saved under data folder, you need to add the data/path

## Inspecting the dataframe

In [4]:
# Is it empty

df.empty

False

In [6]:
# What are the dimensions/size in rows and columns 

df.shape

(10087, 26)

The df has 10086 rows and 26 columns

What columns do we have?
We know there are 26 columns, but what are they? Let's use the columns attribute to see:

In [7]:
# Check the columns

df.columns

Index(['mag', 'place', 'time', 'updated', 'tz', 'url', 'detail', 'felt', 'cdi',
       'mmi', 'alert', 'status', 'tsunami', 'sig', 'net', 'code', 'ids',
       'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'magType', 'type',
       'title'],
      dtype='object')

In [9]:
# View rows from the top with head():

df.head()

mag                              place           time        updated  tz  \
0  4.60  5 km SSE of Reykjanesbær, Iceland  1699659700951  1699662479040 NaN   
1 -0.17                   Alaska Peninsula  1699659556140  1699668903770 NaN   
2  4.50                          Banda Sea  1699658997006  1699660514040 NaN   
3  3.15  4 km WSW of Mayagüez, Puerto Rico  1699657949680  1699659717050 NaN   
4  1.10     31 km SSW of Goldfield, Nevada  1699656768354  1699659341711 NaN   

                                                 url  \
0  https://earthquake.usgs.gov/earthquakes/eventp...   
1  https://earthquake.usgs.gov/earthquakes/eventp...   
2  https://earthquake.usgs.gov/earthquakes/eventp...   
3  https://earthquake.usgs.gov/earthquakes/eventp...   
4  https://earthquake.usgs.gov/earthquakes/eventp...   

                                              detail  felt  cdi  mmi  ...  \
0  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
1  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
2  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
3  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
4  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   

            ids sources                types   nst     dmin     rms     gap  \
0  ,us7000la96,    ,us,  ,origin,phase-data,  47.0  0.94300  0.3700  111.00   
1  ,av91121313,    ,av,  ,origin,phase-data,   6.0      NaN  0.0500  147.00   
2  ,us7000la90,    ,us,  ,origin,phase-data,  29.0  1.57000  0.8200   54.00   
3  ,pr71431213,    ,pr,  ,origin,phase-data,  10.0  0.04183  0.1900  157.00   
4  ,nn00868762,    ,nn,  ,origin,phase-data,  10.0  0.18400  0.1333  122.75   

  magType        type                                      title  
0      mb  earthquake  M 4.6 - 5 km SSE of Reykjanesbær, Iceland  
1      ml  earthquake                  M -0.2 - Alaska Peninsula  
2      mb  earthquake                          M 4.5 - Banda Sea  
3      md  earthquake  M 3.2 - 4 km WSW of Mayagüez, Puerto Rico  
4      ml  earthquake     M 1.1 - 31 km SSW of Goldfield, Nevada  

[5 rows x 26 columns]

In [11]:
# View rows from bottom, lets view 2 rows

df.tail(2)

mag                    place           time        updated  tz  \
10085  1.03     3 km SSW of Cobb, CA  1697069373120  1697072892830 NaN   
10086  0.90  24 km ESE of Julian, CA  1697068830650  1697131563986 NaN   

                                                     url  \
10085  https://earthquake.usgs.gov/earthquakes/eventp...   
10086  https://earthquake.usgs.gov/earthquakes/eventp...   

                                                  detail  felt  cdi  mmi  ...  \
10085  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
10086  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   

                ids sources                                           types  \
10085  ,nc73946205,    ,nc,  ,nearby-cities,origin,phase-data,scitech-link,   
10086  ,ci40581440,    ,ci,  ,nearby-cities,origin,phase-data,scitech-link,   

        nst     dmin   rms    gap magType        type  \
10085  16.0  0.01684  0.03  107.0      md  earthquake   
10086  35.0  0.07059  0.19   71.0      ml  earthquake   

                                 title  
10085     M 1.0 - 3 km SSW of Cobb, CA  
10086  M 0.9 - 24 km ESE of Julian, CA  

[2 rows x 26 columns]

Check for more options https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html

In [14]:
# Check the data type

df.dtypes

mag        float64
place       object
time         int64
updated      int64
tz         float64
url         object
detail      object
felt       float64
cdi        float64
mmi        float64
alert       object
status      object
tsunami      int64
sig          int64
net         object
code        object
ids         object
sources     object
types       object
nst        float64
dmin       float64
rms        float64
gap        float64
magType     object
type        object
title       object
dtype: object

In [16]:
# Getting extra info and finding nulls 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10087 entries, 0 to 10086
Data columns (total 26 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   mag      10087 non-null  float64
 1   place    9622 non-null   object 
 2   time     10087 non-null  int64  
 3   updated  10087 non-null  int64  
 4   tz       0 non-null      float64
 5   url      10087 non-null  object 
 6   detail   10087 non-null  object 
 7   felt     614 non-null    float64
 8   cdi      614 non-null    float64
 9   mmi      130 non-null    float64
 10  alert    69 non-null     object 
 11  status   10087 non-null  object 
 12  tsunami  10087 non-null  int64  
 13  sig      10087 non-null  int64  
 14  net      10087 non-null  object 
 15  code     10087 non-null  object 
 16  ids      10087 non-null  object 
 17  sources  10087 non-null  object 
 18  types    10087 non-null  object 
 19  nst      7751 non-null   float64
 20  dmin     6081 non-null   float64
 21  rms      100

## Describing and Summarizing

Get summary statistics

In [17]:
df.describe()

mag          time       updated   tz          felt  \
count  10087.000000  1.008700e+04  1.008700e+04  0.0    614.000000   
mean       1.632652  1.698323e+12  1.698709e+12  NaN     50.187296   
std        1.254550  7.194027e+08  6.935017e+08  NaN    581.424722   
min       -1.320000  1.697069e+12  1.697071e+12  NaN      0.000000   
25%        0.860000  1.697736e+12  1.698232e+12  NaN      1.000000   
50%        1.400000  1.698308e+12  1.698795e+12  NaN      2.000000   
75%        2.060000  1.698912e+12  1.699315e+12  NaN      5.000000   
max        7.100000  1.699660e+12  1.699832e+12  NaN  11939.000000   

              cdi         mmi       tsunami           sig          nst  \
count  614.000000  130.000000  10087.000000  10087.000000  7751.000000   
mean     2.718078    3.626177      0.000892     65.740755    23.557476   
std      1.407976    1.859809      0.029858     97.619527    23.114716   
min      0.000000    0.000000      0.000000      0.000000     0.000000   
25%      2.000000    2.509500      0.000000     11.000000     9.000000   
50%      2.700000    3.649500      0.000000     30.000000    17.000000   
75%      3.600000    4.528500      0.000000     65.000000    29.000000   
max      8.200000    7.872000      1.000000   1026.000000   378.000000   

              dmin           rms          gap  
count  6081.000000  10086.000000  7750.000000  
mean      0.682834      0.294198   115.024477  
std       2.292356      0.270637    63.344834  
min       0.000000      0.000000    15.000000  
25%       0.013500      0.100000    67.000000  
50%       0.064730      0.180000    99.000000  
75%       0.205700      0.470000   148.000000  
max      45.685000      3.090000   350.000000

Specifying the 5th and 95th percentile:

In [18]:
df.describe(percentiles=[0.05, 0.95])

mag          time       updated   tz          felt  \
count  10087.000000  1.008700e+04  1.008700e+04  0.0    614.000000   
mean       1.632652  1.698323e+12  1.698709e+12  NaN     50.187296   
std        1.254550  7.194027e+08  6.935017e+08  NaN    581.424722   
min       -1.320000  1.697069e+12  1.697071e+12  NaN      0.000000   
5%        -0.080000  1.697200e+12  1.697467e+12  NaN      0.000000   
50%        1.400000  1.698308e+12  1.698795e+12  NaN      2.000000   
95%        4.500000  1.699501e+12  1.699639e+12  NaN     72.050000   
max        7.100000  1.699660e+12  1.699832e+12  NaN  11939.000000   

              cdi         mmi       tsunami           sig          nst  \
count  614.000000  130.000000  10087.000000  10087.000000  7751.000000   
mean     2.718078    3.626177      0.000892     65.740755    23.557476   
std      1.407976    1.859809      0.029858     97.619527    23.114716   
min      0.000000    0.000000      0.000000      0.000000     0.000000   
5%       0.000000    0.000000      0.000000      0.000000     5.000000   
50%      2.700000    3.649500      0.000000     30.000000    17.000000   
95%      4.900000    6.710650      0.000000    312.000000    65.000000   
max      8.200000    7.872000      1.000000   1026.000000   378.000000   

              dmin           rms          gap  
count  6081.000000  10086.000000  7750.000000  
mean      0.682834      0.294198   115.024477  
std       2.292356      0.270637    63.344834  
min       0.000000      0.000000    15.000000  
5%        0.000000      0.020000    41.000000  
50%       0.064730      0.180000    99.000000  
95%       3.719000      0.820000   246.375500  
max      45.685000      3.090000   350.000000

Works in columns too:

In [22]:
# Select a specific column and describe i.e. the column felt

df.felt.describe()

count      614.000000
mean        50.187296
std        581.424722
min          0.000000
25%          1.000000
50%          2.000000
75%          5.000000
max      11939.000000
Name: felt, dtype: float64

In [23]:
# Count the number of non-null observations

df.count()

mag        10087
place       9622
time       10087
updated    10087
tz             0
url        10087
detail     10087
felt         614
cdi          614
mmi          130
alert         69
status     10087
tsunami    10087
sig        10087
net        10087
code       10087
ids        10087
sources    10087
types      10087
nst         7751
dmin        6081
rms        10086
gap         7750
magType    10087
type       10087
title      10087
dtype: int64

In [24]:
# Finding the unique values in the alert column:

df.alert.unique()

array([nan, 'green', 'yellow', 'orange'], dtype=object)

We can then use `value_counts()` to see how many of each unique value we have:

In [25]:
df.alert.value_counts()

alert
green     64
yellow     4
orange     1
Name: count, dtype: int64


There are methods for specific statistics as well. Here is a sampling of them:

- Method:  Description	 Data types
- `count()`	The number of non-null observations	Any
- `nunique()`	The number of unique values	Any
- `sum()`	The total of the values	Numerical or Boolean
- `mean()`	The average of the values	Numerical or Boolean
- `median()`	The median of the values	Numerical
- `min()`	The minimum of the values	Numerical
- `idxmin()`	The index where the minimum values occurs	Numerical
- `max()`	The maximum of the values	Numerical
- `idxmax()`	The index where the maximum value occurs	Numerical
- `abs()`	The absolute values of the data	Numerical
- `std()`	The standard deviation	Numerical
- `var()`	The variance	Numerical
- `cov()`	The covariance between two Series, or a covariance matrix for all column combinations in a DataFrame	Numerical
- `corr()`	The correlation between two Series, or a correlation matrix for all column combinations in a DataFrame	Numerical
- `quantile()`	Calculates a specific quantile	Numerical
- `cumsum()`	The cumulative sum	Numerical or Boolean
- `cummin()`	The cumulative minimum	Numerical
- `cummax()`	The cumulative maximum	Numerical


Note that Index objects also have several methods to help describe and summarize our data:

- Method: Description
- `argmax()/argmin()`: Find the location of the maximum/minimum value in the index
- `equals()`: Compare the index to another Index object for equality
- `isin()`: Check if the index values are in a list of values and return an array of Booleans
- `max()/min()`: Find the maximum/minimum value in the index
- `nunique()`: Get the number of unique values in the index
- `to_series()`: Create a Series object from the index
- `unique()`: Find the unique values of the index
- `value_counts()`: Create a frequency table for the unique values in the index

## Subsetting the Data

Grab an entire column using attribute notation:

In [26]:
df.mag

0        4.60
1       -0.17
2        4.50
3        3.15
4        1.10
         ... 
10082    0.95
10083    1.12
10084    1.40
10085    1.03
10086    0.90
Name: mag, Length: 10087, dtype: float64

Grab an entire column using dictionary syntax:

In [27]:
df['mag']

0        4.60
1       -0.17
2        4.50
3        3.15
4        1.10
         ... 
10082    0.95
10083    1.12
10084    1.40
10085    1.03
10086    0.90
Name: mag, Length: 10087, dtype: float64

You can select multiple columns:

In [28]:
df[['mag', 'title', 'tsunami']]

mag                                           title  tsunami
0      4.60       M 4.6 - 5 km SSE of Reykjanesbær, Iceland        0
1     -0.17                       M -0.2 - Alaska Peninsula        0
2      4.50                               M 4.5 - Banda Sea        0
3      3.15       M 3.2 - 4 km WSW of Mayagüez, Puerto Rico        0
4      1.10          M 1.1 - 31 km SSW of Goldfield, Nevada        0
...     ...                                             ...      ...
10082  0.95             M 1.0 - 3 km ENE of The Geysers, CA        0
10083  1.12             M 1.1 - 3 km ENE of The Geysers, CA        0
10084  1.40  M 1.4 Ice Quake - 115 km NW of Yakutat, Alaska        0
10085  1.03                    M 1.0 - 3 km SSW of Cobb, CA        0
10086  0.90                 M 0.9 - 24 km ESE of Julian, CA        0

[10087 rows x 3 columns]

Selecting columns using list comprehensions and string operations:

In [29]:
df[
    ['title', 'time'] # creates the list
    + [col for col in df.columns if col.startswith('mag')] # select columns starting with 'mag'
]

title           time   mag  \
0           M 4.6 - 5 km SSE of Reykjanesbær, Iceland  1699659700951  4.60   
1                           M -0.2 - Alaska Peninsula  1699659556140 -0.17   
2                                   M 4.5 - Banda Sea  1699658997006  4.50   
3           M 3.2 - 4 km WSW of Mayagüez, Puerto Rico  1699657949680  3.15   
4              M 1.1 - 31 km SSW of Goldfield, Nevada  1699656768354  1.10   
...                                               ...            ...   ...   
10082             M 1.0 - 3 km ENE of The Geysers, CA  1697069851600  0.95   
10083             M 1.1 - 3 km ENE of The Geysers, CA  1697069809590  1.12   
10084  M 1.4 Ice Quake - 115 km NW of Yakutat, Alaska  1697069804213  1.40   
10085                    M 1.0 - 3 km SSW of Cobb, CA  1697069373120  1.03   
10086                 M 0.9 - 24 km ESE of Julian, CA  1697068830650  0.90   

      magType  
0          mb  
1          ml  
2          mb  
3          md  
4          ml  
...       ...  
10082      md  
10083      md  
10084      ml  
10085      md  
10086      ml  

[10087 rows x 4 columns]

## Slicing 

Selecting Rows

In [30]:
# Using row numbers (inclusive of first index, exclusive of last):
    
df[100:103] #selected rows 100 to 102

mag                            place           time        updated  tz  \
100  0.5  6 km NNE of Truckee, California  1699633658816  1699669360657 NaN   
101  1.7    5 km WNW of Anchorage, Alaska  1699633456834  1699633588555 NaN   
102  1.7        40 km W of Mentone, Texas  1699633418271  1699634605784 NaN   

                                                   url  \
100  https://earthquake.usgs.gov/earthquakes/eventp...   
101  https://earthquake.usgs.gov/earthquakes/eventp...   
102  https://earthquake.usgs.gov/earthquakes/eventp...   

                                                detail  felt  cdi  mmi  ...  \
100  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
101  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   
102  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN  ...   

                ids sources                types   nst   dmin     rms     gap  \
100    ,nn00868766,    ,nn,  ,origin,phase-data,   8.0  0.125  0.1583  160.23   
101  ,ak023efkf383,    ,ak,  ,origin,phase-data,   NaN    NaN  0.5100     NaN   
102    ,tx2023wbcz,    ,tx,  ,origin,phase-data,  18.0  0.000  0.3000   43.00   

        magType        type                                    title  
100          ml  earthquake  M 0.5 - 6 km NNE of Truckee, California  
101          ml  earthquake    M 1.7 - 5 km WNW of Anchorage, Alaska  
102  ml(texnet)  earthquake        M 1.7 - 40 km W of Mentone, Texas  

[3 rows x 26 columns]

Selecting rows and columns with chaining

In [31]:
# Select two columns, from rows 100 to 103

df[['title', 'time']][100:103]  # note order doesnt matter, you can start with rows or columns here

title           time
100  M 0.5 - 6 km NNE of Truckee, California  1699633658816
101    M 1.7 - 5 km WNW of Anchorage, Alaska  1699633456834
102        M 1.7 - 40 km W of Mentone, Texas  1699633418271

## Indexing

### Indexing using `loc()`

Note we have to lower the end index by one since loc is inclusive of endpoints:

In [33]:
# We want to select rows 110 - 112, column 'title' and at the same time change the string in title to lower case

df.loc[110:112, 'title'] = df.loc[110:112, 'title'].str.lower()

In [34]:
# View

df.loc[110:112, 'title']

110    m 0.1 - 85 km nw of karluk, alaska
111                              m 1.7 - 
112            m 0.8 - 4 km w of cobb, ca
Name: title, dtype: object

Note that the string in column title has all changed to lower case, and we selected rows 110 to 112

Selection of the format `loc[row_indexer, column_indexer]` where `:` can be used to select all:

In [35]:
# Select all rows, and only column 'title'

df.loc[:,'title']

0             M 4.6 - 5 km SSE of Reykjanesbær, Iceland
1                             M -0.2 - Alaska Peninsula
2                                     M 4.5 - Banda Sea
3             M 3.2 - 4 km WSW of Mayagüez, Puerto Rico
4                M 1.1 - 31 km SSW of Goldfield, Nevada
                              ...                      
10082               M 1.0 - 3 km ENE of The Geysers, CA
10083               M 1.1 - 3 km ENE of The Geysers, CA
10084    M 1.4 Ice Quake - 115 km NW of Yakutat, Alaska
10085                      M 1.0 - 3 km SSW of Cobb, CA
10086                   M 0.9 - 24 km ESE of Julian, CA
Name: title, Length: 10087, dtype: object

We can use loc to select specific rows and columns without chaining. If we use row numbers with `loc`, they are now inclusive of the end index:

In [36]:
# Select rows 10 to 15, and only 2 columns 'title' and 'mag'

df.loc[10:15, ['title', 'mag']]

title   mag
10                            M 3.6 - Mona Passage  3.61
11            M -0.6 - 83 km NNW of Karluk, Alaska -0.55
12  M 2.0 Explosion - 16 km S of Princeton, Canada  2.00
13    M 3.4 - 6 km ENE of La Parguera, Puerto Rico  3.37
14              M 0.6 - 6 km NW of The Geysers, CA  0.57
15            M 1.2 - 55 km SW of Unalaska, Alaska  1.21

### Indexing with `iloc`

Exclusive of the endpoint just as Python slicing:

In [40]:
# Select rows 10 to 15 (will select upto 14) and only columns 25 'title' and 0 'mag'

df.iloc[10:15, [25, 0]]

title   mag
10                            M 3.6 - Mona Passage  3.61
11            M -0.6 - 83 km NNW of Karluk, Alaska -0.55
12  M 2.0 Explosion - 16 km S of Princeton, Canada  2.00
13    M 3.4 - 6 km ENE of La Parguera, Puerto Rico  3.37
14              M 0.6 - 6 km NW of The Geysers, CA  0.57

We can use slicing syntax with iloc for both rows and columns:

In [41]:
# Slice/select rows 10 to 15, columns 6 to 10

df.iloc[10:15, 6:10]

detail  felt  cdi  mmi
10  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN
11  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN
12  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN
13  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN
14  https://earthquake.usgs.gov/fdsnws/event/1/que...   NaN  NaN  NaN

## Filtering

We can filter our dataframes using a Boolean mask, which can be made as follows:

In [42]:
# Filter where in the variable 'mag' is greater than 2

df.mag > 2

0         True
1        False
2         True
3         True
4        False
         ...  
10082    False
10083    False
10084    False
10085    False
10086    False
Name: mag, Length: 10087, dtype: bool

In [43]:
# filter where the mag is greater than or equal to 7.0

df[df.mag >= 7.0]

mag      place           time        updated  tz  \
822  7.1  Banda Sea  1699419230459  1699568379066 NaN   

                                                   url  \
822  https://earthquake.usgs.gov/earthquakes/eventp...   

                                                detail  felt  cdi    mmi  ...  \
822  https://earthquake.usgs.gov/fdsnws/event/1/que...   5.0  7.4  6.194  ...   

              ids sources                                              types  \
822  ,us7000l9h4,    ,us,  ,dyfi,general-text,ground-failure,losspager,mo...   

       nst   dmin   rms   gap magType        type              title  
822  102.0  7.491  0.56  54.0     mww  earthquake  M 7.1 - Banda Sea  

[1 rows x 26 columns]

###  What else can you do with your data?

See for more resources:
https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html